# Generated by Django 3.1.3 on 2020-11-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('fa-facebook-f', 'facebook'), ('fa-instagram', 'instagram'), ('fa-google-plus-g', 'google-plus'), ('fa-linkedin-in', 'linkedin')], max_length=20),
        ),
    ]
