# Generated by Django 3.1.3 on 2020-11-14 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201113_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='sujet',
        ),
    ]
