# Generated by Django 3.1.5 on 2021-01-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_traduction_traductiontranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traductiontranslation',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='traductiontranslation',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='traductiontranslation',
            name='status',
        ),
    ]
