# Generated by Django 3.1.5 on 2021-01-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210112_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='traduction',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='traduction',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='traduction',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
