# Generated by Django 3.1.5 on 2021-01-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210113_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traductiontranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
