# Generated by Django 3.1.5 on 2021-01-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210113_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traductiontranslation',
            options={'default_permissions': ()},
        ),
        migrations.AddField(
            model_name='traductiontranslation',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='traductiontranslation',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='website.traduction'),
        ),
        migrations.AlterField(
            model_name='traductiontranslation',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterUniqueTogether(
            name='traductiontranslation',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='traductiontranslation',
            table=None,
        ),
    ]
