# Generated by Django 3.1.2 on 2020-11-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propriete',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='propriete',
            name='image2',
            field=models.ImageField(default='j1.jpg', upload_to='images/Propriete'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propriete',
            name='image3',
            field=models.ImageField(default='j1.jpg', upload_to='images/Propriete'),
            preserve_default=False,
        ),
    ]
