# Generated by Django 3.1.3 on 2020-11-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20201115_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriete',
            name='agent',
        ),
        migrations.AddField(
            model_name='propriete',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Agent', to='service.agent'),
        ),
    ]
